# Brute Force

In [3]:
def brute_force_decrypt(ciphertext):
    for shift in range(26):
        decrypted_text = caesar_decrypt(ciphertext, shift)
        print(f"Shift {shift}: {decrypted_text}")

def caesar_decrypt(ciphertext, shift):
    decrypted_text = ""
    for char in ciphertext:
        if char.isalpha():
            if char.islower():
                decrypted_text += chr((ord(char) - shift - ord('a')) % 26 + ord('a'))
            else:
                decrypted_text += chr((ord(char) - shift - ord('A')) % 26 + ord('A'))
        else:
            decrypted_text += char
    return decrypted_text

ciphertext = "Naim"
print("Brute Force Decryption for Caesar Cipher:")
brute_force_decrypt(ciphertext)


Brute Force Decryption for Caesar Cipher:
Shift 0: Naim
Shift 1: Mzhl
Shift 2: Lygk
Shift 3: Kxfj
Shift 4: Jwei
Shift 5: Ivdh
Shift 6: Hucg
Shift 7: Gtbf
Shift 8: Fsae
Shift 9: Erzd
Shift 10: Dqyc
Shift 11: Cpxb
Shift 12: Bowa
Shift 13: Anvz
Shift 14: Zmuy
Shift 15: Yltx
Shift 16: Xksw
Shift 17: Wjrv
Shift 18: Viqu
Shift 19: Uhpt
Shift 20: Tgos
Shift 21: Sfnr
Shift 22: Remq
Shift 23: Qdlp
Shift 24: Pcko
Shift 25: Objn


# Caesar Cipher

In [12]:
def caesar_encrypt(plaintext, shift):
    encrypted_text = ""
    for char in plaintext:
        if char.isalpha():
            if char.islower():
                encrypted_text += chr((ord(char) + shift - ord('a')) % 26 + ord('a'))
            else:
                encrypted_text += chr((ord(char) + shift - ord('A')) % 26 + ord('A'))
        else:
            encrypted_text += char
    return encrypted_text

def caesar_decrypt(ciphertext, shift):
    decrypted_text = ""
    for char in ciphertext:
        if char.isalpha():
            if char.islower():
                decrypted_text += chr((ord(char) - shift - ord('a')) % 26 + ord('a'))
            else:
                decrypted_text += chr((ord(char) - shift - ord('A')) % 26 + ord('A'))
        else:
            decrypted_text += char
    return decrypted_text


plaintext = "welcome";
shift = 4
ciphertext = caesar_encrypt(plaintext, shift)
print(f"Caesar Cipher Encryption: {ciphertext}")
plaintext=caesar_decrypt(ciphertext,shift)
print(f"Caesar Cipher Decryption: {plaintext}")

Caesar Cipher Encryption: aipgsqi
Caesar Cipher Decryption: welcome


# Mono Alphabetic

In [13]:
class MonoalphabeticCipher:
    def __init__(self):
        self.normal_char = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i',
                            'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r',
                            's', 't', 'u', 'v', 'w', 'x', 'y', 'z']

        self.coded_char = ['Q', 'W', 'E', 'R', 'T', 'Y', 'U', 'I', 'O',
                           'P', 'A', 'S', 'D', 'F', 'G', 'H', 'J', 'K',
                           'L', 'Z', 'X', 'C', 'V', 'B', 'N', 'M']

    def string_encryption(self, s):
        encrypted_string = ""
        for char in s:
            for i in range(26):
                if char == self.normal_char[i]:
                    encrypted_string += self.coded_char[i]
                    break
                elif char < 'a' or char > 'z':
                    encrypted_string += char
                    break
        return encrypted_string

    def string_decryption(self, s):
        decrypted_string = ""
        for char in s:
            for i in range(26):
                if char == self.coded_char[i]:
                    decrypted_string += self.normal_char[i]
                    break
                elif char < 'A' or char > 'Z':
                    decrypted_string += char
                    break
        return decrypted_string


def main():
    cipher = MonoalphabeticCipher()
    plain_text = "Welcome to geeksforgeeks"

    print("Plain text:", plain_text)

    # Changing the whole string to lowercase
    encrypted_message = cipher.string_encryption(plain_text.lower())
    print("Encrypted message:", encrypted_message)

    decrypted_message = cipher.string_decryption(encrypted_message)
    print("Decrypted message:", decrypted_message)


if __name__ == "__main__":
    main()


Plain text: Welcome to geeksforgeeks
Encrypted message: VTSEGDT ZG UTTALYGKUTTAL
Decrypted message: welcome to geeksforgeeks


# Play Fair

In [15]:
def playfair_cipher(plaintext, key, mode):
    # Define the alphabet, excluding 'j'
    alphabet = 'abcdefghiklmnopqrstuvwxyz'
    # Remove whitespace and 'j' from the key and convert to lowercase
    key = key.lower().replace(' ', '').replace('j', 'i')
    # Construct the key square
    key_square = ''
    for letter in key + alphabet:
        if letter not in key_square:
            key_square += letter
    # Split the plaintext into digraphs, padding with 'x' if necessary
    plaintext = plaintext.lower().replace(' ', '').replace('j', 'i')
    if len(plaintext) % 2 == 1:
        plaintext += 'x'
    digraphs = [plaintext[i:i+2] for i in range(0, len(plaintext), 2)]
    # Define the encryption/decryption functions
    def encrypt(digraph):
        a, b = digraph
        row_a, col_a = divmod(key_square.index(a), 5)
        row_b, col_b = divmod(key_square.index(b), 5)
        if row_a == row_b:
            col_a = (col_a + 1) % 5
            col_b = (col_b + 1) % 5
        elif col_a == col_b:
            row_a = (row_a + 1) % 5
            row_b = (row_b + 1) % 5
        else:
            col_a, col_b = col_b, col_a
        return key_square[row_a*5+col_a] + key_square[row_b*5+col_b]

    def decrypt(digraph):
        a, b = digraph
        row_a, col_a = divmod(key_square.index(a), 5)
        row_b, col_b = divmod(key_square.index(b), 5)
        if row_a == row_b:
            col_a = (col_a - 1) % 5
            col_b = (col_b - 1) % 5
        elif col_a == col_b:
            row_a = (row_a - 1) % 5
            row_b = (row_b - 1) % 5
        else:
            col_a, col_b = col_b, col_a
        return key_square[row_a*5+col_a] + key_square[row_b*5+col_b]
    # Encrypt or decrypt the plaintext
    result = ''
    for digraph in digraphs:
        if mode == 'encrypt':
            result += encrypt(digraph)
        elif mode == 'decrypt':
            result += decrypt(digraph)

    # Return the result
    return result

# Example usage
plaintext = 'we are happy today'
key = 'ICE'
ciphertext = playfair_cipher(plaintext, key, 'encrypt')
print(ciphertext)  # outputs: "iisggymlgmsyjqu"
decrypted_text = playfair_cipher(ciphertext, key, 'decrypt')
print(decrypted_text)  # (Note: 'x' is added as padding)

xcctagboozythizy
wearehappytodayx


# Poly Alphabetic

In [16]:

def generateKey(string, key):
	key = list(key)
	if len(string) == len(key):
		return(key)
	else:
		for i in range(len(string) -
					len(key)):
			key.append(key[i % len(key)])
	return("" . join(key))
	
# This function returns the 
# encrypted text generated 
# with the help of the key
def cipherText(string, key):
	cipher_text = []
	for i in range(len(string)):
		x = (ord(string[i]) +
			ord(key[i])) % 26
		x += ord('A')
		cipher_text.append(chr(x))
	return("" . join(cipher_text))
	
# This function decrypts the 
# encrypted text and returns 
# the original text
def originalText(cipher_text, key):
	orig_text = []
	for i in range(len(cipher_text)):
		x = (ord(cipher_text[i]) -
			ord(key[i]) + 26) % 26
		x += ord('A')
		orig_text.append(chr(x))
	return("" . join(orig_text))
	
# Driver code
if __name__ == "__main__":
	string = "GEEKSFORGEEKS"
	keyword = "AYUSH"
	key = generateKey(string, keyword)
	cipher_text = cipherText(string,key)
	print("Ciphertext :", cipher_text)
	print("Original/Decrypted Text :", 
		originalText(cipher_text, key))


Ciphertext : GCYCZFMLYLEIM
Original/Decrypted Text : GEEKSFORGEEKS


# RSA Algorithm

In [17]:
import random
from sympy import mod_inverse, isprime

def generate_keypair(bits):
    # Step 1: Choose two large prime numbers
    p = generate_prime(bits)
    q = generate_prime(bits)

    # Step 2: Compute n (modulus) and phi(n)
    n = p * q
    phi_n = (p - 1) * (q - 1)

    # Step 3: Choose e (public exponent)
    e = choose_public_exponent(phi_n)

    # Step 4: Compute d (private exponent)
    d = mod_inverse(e, phi_n)

    # Public key: (e, n), Private key: (d, n)
    return ((e, n), (d, n))

def generate_prime(bits):
    # Generate a large prime number with a specified number of bits
    while True:
        candidate = random.getrandbits(bits)
        if isprime(candidate):
            return candidate

def choose_public_exponent(phi_n):
    # Choose a public exponent (commonly 65537)
    e = 65537
    while True:
        if isprime(e) and e < phi_n and phi_n % e != 0:
            return e
        e += 2

def encrypt(message, public_key):
    e, n = public_key
    cipher = [pow(ord(char), e, n) for char in message]
    return cipher

def decrypt(ciphertext, private_key):
    d, n = private_key
    decrypted = [chr(pow(char, d, n)) for char in ciphertext]
    return ''.join(decrypted)

# Example usage:
message = "HELLO, RSA!"
bits = 1024

# Generate keypair
public_key, private_key = generate_keypair(bits)

# Encrypt the message
ciphertext = encrypt(message, public_key)
print(f"Original Message: {message}")
print(f"Ciphertext: {ciphertext}")

# Decrypt the ciphertext
decrypted_message = decrypt(ciphertext, private_key)
print(f"Decrypted Message: {decrypted_message}")


Original Message: HELLO, RSA!
Ciphertext: [10339181505457283329472546005821658318810753854576076821687326601534262512735230195843663709607701944409772292294901421340534254073583926557486030172659235937505318250411211310525821252170967812257256557296182628404489650695035677331342013845384136755633259471961337546141928351888118796735588892804123300954149607947862777988571714350539611906142318397856227883989171090970978577568991977687805652238769230943259949375402495858696983967722225010868208605034590404047535653231167544461097644286617868256711841663578818660033199003951232961170961038875608695419349148536713801622313463898956366044790212538526857241560, 11880067519273547570600100990434618115497313165449062594436353310798952682085770937979572442323547040837408583940885273332249959570338287147311051952365044766171515801882611014664132673416143122831680415244823364415420893053235321063396697906798212443805840231975235398542675756728161657213557229437479018391118401454399225008096766909255

In [21]:
from Cryptography.PublicKey import RSA
from Cryptography import Random
from Cryptography.Cipher import PKCS1_OAEP

def rsa_encrypt_decrypt():
    key = RSA.generate(2048)
    private_key = key.export_key('PEM')
    public_key = key.publickey().exportKey('PEM')
    message = input('plain text for RSA encryption and decryption:')
    message = str.encode(message)

    rsa_public_key = RSA.importKey(public_key)
    rsa_public_key = PKCS1_OAEP.new(rsa_public_key)
    encrypted_text = rsa_public_key.encrypt(message)
    #encrypted_text = b64encode(encrypted_text)

    print('your encrypted_text is : {}'.format(encrypted_text))


    rsa_private_key = RSA.importKey(private_key)
    rsa_private_key = PKCS1_OAEP.new(rsa_private_key)
    decrypted_text = rsa_private_key.decrypt(encrypted_text)

    print('your decrypted_text is : {}'.format(decrypted_text))

ModuleNotFoundError: No module named 'Cryptography'

# Hill Cipher

In [3]:

import numpy as np
import sympy
import string
import random

# Define variables
dimension = 3 # Your N
key = np.matrix([[17,17,5], [21,18,21], [2,2,19]]) # Your key
message = 'paymoremoney' # Your message

print("Plain Text: "+message)
print("Key Matrix: ")
print(key)
# Generate the alphabet
alphabet = string.ascii_lowercase

# Encrypted message
encryptedMessage = ""

# Group message in vectors and generate crypted message
for index, i in enumerate(message): #PAYMOREMONEY 
    values = []
    # Make bloc of N values
    if index % dimension == 0:
        for j in range(0, dimension):
            if(index + j < len(message)):
                values.append([alphabet.index(message[index + j])])
                # print(f'if:{values}')
            else:
                values.append([random.randint(0,25)])
                # print(f'else:{values}')
        # Generate vectors and work with them
        vector = np.matrix(values)
        vector = key * vector
        vector %= 26
        for j in range(0, dimension):
            encryptedMessage += alphabet[vector.item(j)]

# Show the result
print("Encrypted message is: "+ encryptedMessage.upper())

#DECRYPTION

def modulo_multiplicative_inverse(A, M):

    # This will iterate from 0 to M-1
    for i in range(0, M):
        # If we have our multiplicative inverse then return it
        if (A*i) % M == 1:
            return i
    # If we didn't find the multiplicative inverse in the loop above
    # then it doesn't exist for A under M
    return -1


matrix= sympy.Matrix([[17,17,5], [21,18,21], [2,2,19]])
adj=(matrix.adjugate()%26) #TO FIND ADJOINT OF KEY MATRIX

mat=np.matrix([[17,17,5], [21,18,21], [2,2,19]])

det=(round(np.linalg.det(mat))%26) #TO FIND DETERMINENT

# print(det)
# print(adj)

mult_inverse=modulo_multiplicative_inverse(det, 26)

# print(mult_inverse)

inv_m=(mult_inverse*adj)%26
print("inverse of Key Matrix: ")
print(inv_m)

decryptedMessage=""

for index, i in enumerate(encryptedMessage): 
    values = []
    if index % dimension == 0:
        for j in range(0, dimension):
            if(index + j < len(encryptedMessage)):
                values.append([alphabet.index(encryptedMessage[index + j])])
            else:
                values.append([random.randint(0,25)])
        vector = np.matrix(values)
        vector = inv_m * vector
        vector %= 26
        for j in range(0, dimension):
            decryptedMessage += alphabet[vector[j]]

# Show the result
print("Decrypted Message: "+ decryptedMessage)

Plain Text: paymoremoney
Key Matrix: 
[[17 17  5]
 [21 18 21]
 [ 2  2 19]]
Encrypted message is: LNSHDLEWMTRW
inverse of Key Matrix: 
Matrix([[4, 9, 15], [15, 17, 6], [24, 0, 17]])
Decrypted Message: paymoremoney


In [30]:
import numpy as np
import string
import random

# Define variables
dimension = 2  # Change the dimension to 2 for a 2x2 matrix
key = np.matrix([[6, 24], [13, 16]])  # Your 2x2 key matrix
message = 'HELP'  # Your message

print("Plain Text: " + message)
print("Key Matrix: ")
print(key)

# Generate the alphabet
alphabet = string.ascii_uppercase

# Encrypted message
encryptedMessage = ""

# Group message in vectors and generate encrypted message
for index in range(0, len(message), dimension):
    values = []
    for j in range(dimension):
        if index + j < len(message):
            values.append([alphabet.index(message[index + j])])
        else:
            values.append([random.randint(0, 25)])
    # Generate vectors and work with them
    vector = np.matrix(values)
    vector = key * vector
    vector %= 26
    for j in range(dimension):
        encryptedMessage += alphabet[vector.item(j)]

# Show the result
print("Encrypted message is: " + encryptedMessage)

# Decryption

# Find the determinant of the 2x2 key matrix
det = (key[0, 0] * key[1, 1] - key[0, 1] * key[1, 0]) % 26

# Find the multiplicative inverse of the determinant modulo 26
mult_inverse = -1
for i in range(26):
    if (det * i) % 26 == 1:
        mult_inverse = i
        break

# Calculate the adjugate of the 2x2 key matrix
adj = np.matrix([[key[1, 1], -key[0, 1]], [-key[1, 0], key[0, 0]]]) % 26

# Calculate the inverse of the key matrix
inv_m = (mult_inverse * adj) % 26

print("Inverse of Key Matrix: ")
print(inv_m)

decryptedMessage = ""

for index in range(0, len(encryptedMessage), dimension):
    values = []
    for j in range(dimension):
        if index + j < len(encryptedMessage):
            values.append([alphabet.index(encryptedMessage[index + j])])
    vector = np.matrix(values)
    vector = inv_m * vector
    vector %= 26
    for j in range(dimension):
        decryptedMessage += alphabet[vector.item(j)]  # Access the individual element

# Show the result
print("Decrypted Message: " + decryptedMessage)


Plain Text: HELP
Key Matrix: 
[[ 6 24]
 [13 16]]
Encrypted message is: IZKT
Inverse of Key Matrix: 
[[10 24]
 [13 20]]
Decrypted Message: EGKQ


# Rail Fence cipher

In [9]:

def encrypt(text, key):
    rail = [['\n' for i in range(len(text))]
            for j in range(key)]
    dir_down = False
    row, col = 0, 0

    for i in range(len(text)):
        if (row == 0) or (row == key - 1):
            dir_down = not dir_down
        rail[row][col] = text[i]
        col += 1
        if dir_down:
            row += 1
        else:
            row -= 1
    result = []
    for i in range(key):
        for j in range(len(text)):
            if rail[i][j] != '\n':
                result.append(rail[i][j])
    return ("".join(result))
# function to decrypt a message
def decrypt(cipher, key):
    rail = [['\n' for i in range(len(cipher))]
            for j in range(key)]
    dir_down = None
    row, col = 0, 0
    for i in range(len(cipher)):
        if row == 0:
            dir_down = True
        if row == key - 1:
            dir_down = False
        rail[row][col] = '*'
        col += 1
        if dir_down:
            row += 1
        else:
            row -= 1
    index = 0
    for i in range(key):
        for j in range(len(cipher)):
            if ((rail[i][j] == '*') and
                    (index < len(cipher))):
                rail[i][j] = cipher[index]
                index += 1
    result = []
    row, col = 0, 0
    for i in range(len(cipher)):
        if row == 0:
            dir_down = True
        if row == key - 1:
            dir_down = False
        if (rail[row][col] != '*'):
            result.append(rail[row][col])
            col += 1
        if dir_down:
            row += 1
        else:
            row -= 1
    return ("".join(result))


# Driver code
if __name__ == "__main__":
    print("Enter your Text:")
    x = input()
    print("Encrypted text is : ")
    y = encrypt(x, 2)
    print(y)
    print("Decrypted text is : ")
    print(decrypt(y, 2))



Enter your Text:


 naim naim naim


Encrypted text is : 
ni amniamni am
Decrypted text is : 
naim naim naim
